name: Production deployment

on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www/caresfoundation/frontend/web
            git stash
            git stash clear
            git pull origin production
            chmod +x .docker/deploy.sh
            sh .docker/deploy.sh medpluscares-prod
